// <auto-generated />
namespace SchoolApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removeEmailRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeEmailRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201306172112225_removeEmailRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
