// <auto-generated />
namespace SchoolApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addParents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addParents));
        
        string IMigrationMetadata.Id
        {
            get { return "201303170249448_addParents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
