// <auto-generated />
namespace SchoolApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserGroupInstanceUseEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserGroupInstanceUseEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "201302192335517_UserGroupInstance-UseEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
