// <auto-generated />
namespace SchoolApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addREcurrenceRule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addREcurrenceRule));
        
        string IMigrationMetadata.Id
        {
            get { return "201303180210546_addREcurrenceRule"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
