// <auto-generated />
namespace SchoolApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addPhotoToUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPhotoToUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201306032141067_addPhotoToUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
