// <auto-generated />
namespace SchoolApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addGroupIntersectionAndDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addGroupIntersectionAndDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201305101720126_addGroupIntersectionAndDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
