// <auto-generated />
namespace DefaultConnection.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removeGroupIdanduserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeGroupIdanduserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201302122344541_removeGroupIdanduserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
